# Generated by Django 2.2.1 on 2019-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='info',
            field=models.CharField(blank=True, max_length=255, verbose_name='info'),
        ),
    ]
