# Generated by Django 2.2.1 on 2019-05-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0011_document_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='info',
        ),
        migrations.AddField(
            model_name='document',
            name='GroupID',
            field=models.IntegerField(blank=True, default=0, verbose_name='图像批次'),
        ),
        migrations.AddField(
            model_name='document',
            name='Info',
            field=models.CharField(blank=True, max_length=255, verbose_name='信息'),
        ),
    ]
