# Generated by Django 2.2.1 on 2019-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190526_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='BatchNum',
            field=models.CharField(blank=True, default='请上传说明文档', max_length=255, verbose_name='产品批号'),
        ),
        migrations.AddField(
            model_name='customimage',
            name='Specs',
            field=models.CharField(blank=True, default='请上传说明文档', max_length=255, verbose_name='产品规格'),
        ),
    ]
