# Generated by Django 2.2.1 on 2019-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190526_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='DefectType',
            field=models.CharField(blank=True, choices=[(None, '无瑕疵'), ('油污', '油污'), ('浆斑', '浆斑'), ('停车痕（紧）', '停车痕（紧）'), ('停车痕（松）', '停车痕（松）'), ('并纬', '并纬'), ('擦白', '擦白'), ('擦伤', '擦伤'), ('糙纬', '糙纬'), ('错花', '错花'), ('断经1', '断经1'), ('断经2', '断经2'), ('断纬', '断纬'), ('尽机', '尽机'), ('经条', '经条'), ('空织', '空织'), ('起机', '起机'), ('缺纬1', '缺纬1'), ('缺纬2', '缺纬2'), ('缩纬', '缩纬'), ('折返', '折返'), ('其他', '其他')], max_length=255, verbose_name='瑕疵类别'),
        ),
    ]
