# Generated by Django 2.2.1 on 2019-05-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClothCode', models.CharField(blank=True, default='000000', max_length=255, verbose_name='布匹编号')),
                ('BatchNum', models.CharField(blank=True, default='请上传说明文档', max_length=255, verbose_name='产品批号')),
                ('Specs', models.CharField(blank=True, default='请上传说明文档', max_length=255, verbose_name='产品规格')),
                ('CountAll', models.BigIntegerField(verbose_name='总数')),
                ('DefectCount', models.BigIntegerField(verbose_name='次品数')),
                ('YW', models.BigIntegerField(verbose_name='油污')),
                ('JB', models.BigIntegerField(verbose_name='浆斑')),
                ('TCHJ', models.BigIntegerField(verbose_name='停车痕（紧）')),
                ('TCHS', models.BigIntegerField(verbose_name='停车痕（松）')),
                ('BW', models.BigIntegerField(verbose_name='并纬')),
                ('CB', models.BigIntegerField(verbose_name='擦白')),
                ('CS', models.BigIntegerField(verbose_name='擦伤')),
                ('CW', models.BigIntegerField(verbose_name='糙纬')),
                ('CH', models.BigIntegerField(verbose_name='错花')),
                ('DJ1', models.BigIntegerField(verbose_name='断经1')),
                ('DJ2', models.BigIntegerField(verbose_name='断经2')),
                ('DW', models.BigIntegerField(verbose_name='断纬')),
                ('JJ', models.BigIntegerField(verbose_name='尽机')),
                ('JT', models.BigIntegerField(verbose_name='经条')),
                ('KZ', models.BigIntegerField(verbose_name='空织')),
                ('QJ', models.BigIntegerField(verbose_name='起机')),
                ('QW1', models.BigIntegerField(verbose_name='缺纬1')),
                ('QW2', models.BigIntegerField(verbose_name='缺纬2')),
                ('SW', models.BigIntegerField(verbose_name='缩纬')),
                ('ZF', models.BigIntegerField(verbose_name='折返')),
                ('QT', models.BigIntegerField(verbose_name='其他')),
            ],
        ),
    ]
