# Generated by Django 2.2.1 on 2019-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticsdetail',
            name='BW',
            field=models.BigIntegerField(default=0, verbose_name='并纬'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='CB',
            field=models.BigIntegerField(default=0, verbose_name='擦白'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='CH',
            field=models.BigIntegerField(default=0, verbose_name='错花'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='CS',
            field=models.BigIntegerField(default=0, verbose_name='擦伤'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='CW',
            field=models.BigIntegerField(default=0, verbose_name='糙纬'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='CountAll',
            field=models.BigIntegerField(default=0, verbose_name='总数'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='DJ1',
            field=models.BigIntegerField(default=0, verbose_name='断经1'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='DJ2',
            field=models.BigIntegerField(default=0, verbose_name='断经2'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='DW',
            field=models.BigIntegerField(default=0, verbose_name='断纬'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='DefectCount',
            field=models.BigIntegerField(default=0, verbose_name='次品数'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='JB',
            field=models.BigIntegerField(default=0, verbose_name='浆斑'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='JJ',
            field=models.BigIntegerField(default=0, verbose_name='尽机'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='JT',
            field=models.BigIntegerField(default=0, verbose_name='经条'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='KZ',
            field=models.BigIntegerField(default=0, verbose_name='空织'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='QJ',
            field=models.BigIntegerField(default=0, verbose_name='起机'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='QT',
            field=models.BigIntegerField(default=0, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='QW1',
            field=models.BigIntegerField(default=0, verbose_name='缺纬1'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='QW2',
            field=models.BigIntegerField(default=0, verbose_name='缺纬2'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='SW',
            field=models.BigIntegerField(default=0, verbose_name='缩纬'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='TCHJ',
            field=models.BigIntegerField(default=0, verbose_name='停车痕（紧）'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='TCHS',
            field=models.BigIntegerField(default=0, verbose_name='停车痕（松）'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='YW',
            field=models.BigIntegerField(default=0, verbose_name='油污'),
        ),
        migrations.AlterField(
            model_name='staticsdetail',
            name='ZF',
            field=models.BigIntegerField(default=0, verbose_name='折返'),
        ),
    ]
